//! Pine Script v6 code generation.
//!
//! Generates TradingView Pine Script from strategy artifacts.

use crate::artifact::{ComponentArtifact, StrategyArtifact};
use crate::error::{ExportError, ExportResult};
use std::fmt::Write;
use std::path::Path;

/// Pine Script generator.
pub struct PineGenerator {
    /// Include debug comments in output.
    pub include_comments: bool,
    /// Strategy title override.
    pub title_override: Option<String>,
}

impl Default for PineGenerator {
    fn default() -> Self {
        Self {
            include_comments: true,
            title_override: None,
        }
    }
}

impl PineGenerator {
    /// Create a new Pine generator.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set whether to include comments.
    pub fn with_comments(mut self, include: bool) -> Self {
        self.include_comments = include;
        self
    }

    /// Override the strategy title.
    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title_override = Some(title.into());
        self
    }

    /// Generate Pine Script from artifact.
    pub fn generate(&self, artifact: &StrategyArtifact) -> ExportResult<String> {
        let mut pine = String::with_capacity(4096);

        // Header
        self.write_header(&mut pine, artifact)?;

        // Inputs
        self.write_inputs(&mut pine, artifact)?;

        // Signal generator logic
        self.write_signal_logic(&mut pine, &artifact.signal_generator)?;

        // Position manager logic (exit conditions)
        self.write_position_logic(&mut pine, &artifact.position_manager)?;

        // Filter logic (optional)
        if let Some(ref filter) = artifact.signal_filter {
            self.write_filter_logic(&mut pine, filter)?;
        }

        // Entry/exit logic
        self.write_entry_exit(&mut pine, artifact)?;

        // Plotting
        self.write_plotting(&mut pine, artifact)?;

        Ok(pine)
    }

    /// Generate and save to file.
    pub fn generate_to_file(&self, artifact: &StrategyArtifact, path: &Path) -> ExportResult<()> {
        let pine = self.generate(artifact)?;
        std::fs::write(path, pine)?;
        Ok(())
    }

    fn write_header(&self, pine: &mut String, artifact: &StrategyArtifact) -> ExportResult<()> {
        let title = self
            .title_override
            .clone()
            .unwrap_or_else(|| artifact.description());

        writeln!(pine, "//@version=6")?;
        writeln!(
            pine,
            "strategy(\"{}\", overlay=true, pyramiding=0, default_qty_type=strategy.percent_of_equity, default_qty_value=100)",
            title
        )?;
        writeln!(pine)?;

        if self.include_comments {
            writeln!(pine, "// Generated by TrendLab v2")?;
            writeln!(pine, "// Artifact ID: {}", artifact.strategy_id)?;
            writeln!(pine, "// Exported: {}", artifact.exported_at)?;
            writeln!(pine)?;
        }

        Ok(())
    }

    fn write_inputs(&self, pine: &mut String, artifact: &StrategyArtifact) -> ExportResult<()> {
        if self.include_comments {
            writeln!(pine, "// ===== INPUTS =====")?;
        }

        // Signal generator inputs
        self.write_component_inputs(pine, &artifact.signal_generator, "sig")?;

        // Position manager inputs
        self.write_component_inputs(pine, &artifact.position_manager, "pm")?;

        // Filter inputs (if present)
        if let Some(ref filter) = artifact.signal_filter {
            self.write_component_inputs(pine, filter, "flt")?;
        }

        writeln!(pine)?;
        Ok(())
    }

    fn write_component_inputs(
        &self,
        pine: &mut String,
        component: &ComponentArtifact,
        prefix: &str,
    ) -> ExportResult<()> {
        use crate::artifact::ParamArtifact;

        for (name, value) in &component.parameters {
            let input_name = format!("{}_{}", prefix, name);
            match value {
                ParamArtifact::Int(v) => {
                    writeln!(
                        pine,
                        "{} = input.int({}, title=\"{} {}\")",
                        input_name,
                        v,
                        component.name,
                        name
                    )?;
                }
                ParamArtifact::Float(v) => {
                    writeln!(
                        pine,
                        "{} = input.float({}, title=\"{} {}\")",
                        input_name,
                        v,
                        component.name,
                        name
                    )?;
                }
                ParamArtifact::Bool(v) => {
                    writeln!(
                        pine,
                        "{} = input.bool({}, title=\"{} {}\")",
                        input_name,
                        if *v { "true" } else { "false" },
                        component.name,
                        name
                    )?;
                }
                ParamArtifact::String(v) => {
                    writeln!(
                        pine,
                        "{} = input.string(\"{}\", title=\"{} {}\")",
                        input_name,
                        v,
                        component.name,
                        name
                    )?;
                }
            }
        }

        Ok(())
    }

    fn write_signal_logic(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        if self.include_comments {
            writeln!(pine, "// ===== SIGNAL: {} =====", signal.name)?;
        }

        match signal.name.as_str() {
            "DonchianBreakout" | "donchian_breakout" => {
                self.write_donchian_signal(pine, signal)?;
            }
            "FiftyTwoWeekBreakout" | "fifty_two_week" | "52_week_breakout" => {
                self.write_52_week_signal(pine, signal)?;
            }
            "MaCrossover" | "ma_crossover" => {
                self.write_ma_crossover_signal(pine, signal)?;
            }
            "Supertrend" | "supertrend" => {
                self.write_supertrend_signal(pine, signal)?;
            }
            "Momentum" | "momentum" | "tsmom" => {
                self.write_momentum_signal(pine, signal)?;
            }
            "BollingerBreakout" | "bollinger_breakout" => {
                self.write_bollinger_signal(pine, signal)?;
            }
            "KeltnerBreakout" | "keltner_breakout" => {
                self.write_keltner_signal(pine, signal)?;
            }
            "ParabolicSar" | "parabolic_sar" => {
                self.write_parabolic_sar_signal(pine, signal)?;
            }
            "RocMomentum" | "roc" | "roc_momentum" => {
                self.write_roc_signal(pine, signal)?;
            }
            "AroonCrossover" | "aroon" | "aroon_crossover" => {
                self.write_aroon_signal(pine, signal)?;
            }
            "TrendFlip" | "trend_flip" => {
                self.write_trend_flip_signal(pine, signal)?;
            }
            _ => {
                return Err(ExportError::UnsupportedComponent {
                    component: signal.name.clone(),
                });
            }
        }

        writeln!(pine)?;
        Ok(())
    }

    fn write_donchian_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let lookback = signal.get_int_or("lookback", 20);
        let long_only = signal.get_bool_or("long_only", false);

        writeln!(pine, "donchian_high = ta.highest(high, sig_lookback)[1]")?;
        writeln!(pine, "donchian_low = ta.lowest(low, sig_lookback)[1]")?;
        writeln!(pine, "long_signal = close > donchian_high")?;
        if long_only {
            writeln!(pine, "short_signal = false")?;
        } else {
            writeln!(pine, "short_signal = close < donchian_low")?;
        }

        // Provide defaults if no input defined
        if !signal.parameters.contains_key("lookback") {
            writeln!(
                pine,
                "sig_lookback = input.int({}, title=\"Donchian Lookback\")",
                lookback
            )?;
        }

        Ok(())
    }

    fn write_52_week_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let lookback = signal.get_int_or("lookback", 252);

        writeln!(pine, "yearly_high = ta.highest(high, sig_lookback)[1]")?;
        writeln!(pine, "yearly_low = ta.lowest(low, sig_lookback)[1]")?;
        writeln!(pine, "long_signal = close > yearly_high")?;
        writeln!(pine, "short_signal = close < yearly_low")?;

        if !signal.parameters.contains_key("lookback") {
            writeln!(
                pine,
                "sig_lookback = input.int({}, title=\"52-Week Lookback\")",
                lookback
            )?;
        }

        Ok(())
    }

    fn write_ma_crossover_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let fast = signal.get_int_or("fast_period", 20);
        let slow = signal.get_int_or("slow_period", 50);

        if !signal.parameters.contains_key("fast_period") {
            writeln!(pine, "sig_fast_period = input.int({}, title=\"Fast MA\")", fast)?;
        }
        if !signal.parameters.contains_key("slow_period") {
            writeln!(pine, "sig_slow_period = input.int({}, title=\"Slow MA\")", slow)?;
        }

        writeln!(pine, "fast_ma = ta.sma(close, sig_fast_period)")?;
        writeln!(pine, "slow_ma = ta.sma(close, sig_slow_period)")?;
        writeln!(pine, "long_signal = ta.crossover(fast_ma, slow_ma)")?;
        writeln!(pine, "short_signal = ta.crossunder(fast_ma, slow_ma)")?;

        Ok(())
    }

    fn write_supertrend_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let period = signal.get_int_or("period", 10);
        let multiplier = signal.get_float_or("multiplier", 3.0);

        if !signal.parameters.contains_key("period") {
            writeln!(
                pine,
                "sig_period = input.int({}, title=\"Supertrend Period\")",
                period
            )?;
        }
        if !signal.parameters.contains_key("multiplier") {
            writeln!(
                pine,
                "sig_multiplier = input.float({}, title=\"Supertrend Multiplier\")",
                multiplier
            )?;
        }

        writeln!(pine, "[supertrend, direction] = ta.supertrend(sig_multiplier, sig_period)")?;
        writeln!(pine, "long_signal = direction < 0 and direction[1] > 0")?;
        writeln!(pine, "short_signal = direction > 0 and direction[1] < 0")?;

        Ok(())
    }

    fn write_momentum_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let lookback = signal.get_int_or("lookback", 252);

        if !signal.parameters.contains_key("lookback") {
            writeln!(
                pine,
                "sig_lookback = input.int({}, title=\"Momentum Lookback\")",
                lookback
            )?;
        }

        writeln!(pine, "momentum = close / close[sig_lookback] - 1")?;
        writeln!(pine, "long_signal = momentum > 0 and momentum[1] <= 0")?;
        writeln!(pine, "short_signal = momentum < 0 and momentum[1] >= 0")?;

        Ok(())
    }

    fn write_bollinger_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let period = signal.get_int_or("period", 20);
        let std_dev = signal.get_float_or("std_dev", 2.0);

        if !signal.parameters.contains_key("period") {
            writeln!(
                pine,
                "sig_period = input.int({}, title=\"Bollinger Period\")",
                period
            )?;
        }
        if !signal.parameters.contains_key("std_dev") {
            writeln!(
                pine,
                "sig_std_dev = input.float({}, title=\"Bollinger StdDev\")",
                std_dev
            )?;
        }

        writeln!(pine, "[bb_middle, bb_upper, bb_lower] = ta.bb(close, sig_period, sig_std_dev)")?;
        writeln!(pine, "long_signal = close > bb_upper")?;
        writeln!(pine, "short_signal = close < bb_lower")?;

        Ok(())
    }

    fn write_keltner_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let period = signal.get_int_or("period", 20);
        let multiplier = signal.get_float_or("multiplier", 2.0);

        if !signal.parameters.contains_key("period") {
            writeln!(
                pine,
                "sig_period = input.int({}, title=\"Keltner Period\")",
                period
            )?;
        }
        if !signal.parameters.contains_key("multiplier") {
            writeln!(
                pine,
                "sig_multiplier = input.float({}, title=\"Keltner Multiplier\")",
                multiplier
            )?;
        }

        writeln!(pine, "kc_basis = ta.ema(close, sig_period)")?;
        writeln!(pine, "kc_atr = ta.atr(sig_period)")?;
        writeln!(pine, "kc_upper = kc_basis + sig_multiplier * kc_atr")?;
        writeln!(pine, "kc_lower = kc_basis - sig_multiplier * kc_atr")?;
        writeln!(pine, "long_signal = close > kc_upper")?;
        writeln!(pine, "short_signal = close < kc_lower")?;

        Ok(())
    }

    fn write_parabolic_sar_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let start = signal.get_float_or("start", 0.02);
        let increment = signal.get_float_or("increment", 0.02);
        let max = signal.get_float_or("max", 0.2);

        if !signal.parameters.contains_key("start") {
            writeln!(
                pine,
                "sig_start = input.float({}, title=\"SAR Start\")",
                start
            )?;
        }
        if !signal.parameters.contains_key("increment") {
            writeln!(
                pine,
                "sig_increment = input.float({}, title=\"SAR Increment\")",
                increment
            )?;
        }
        if !signal.parameters.contains_key("max") {
            writeln!(pine, "sig_max = input.float({}, title=\"SAR Max\")", max)?;
        }

        writeln!(pine, "sar = ta.sar(sig_start, sig_increment, sig_max)")?;
        writeln!(pine, "long_signal = close > sar and close[1] <= sar[1]")?;
        writeln!(pine, "short_signal = close < sar and close[1] >= sar[1]")?;

        Ok(())
    }

    fn write_roc_signal(&self, pine: &mut String, signal: &ComponentArtifact) -> ExportResult<()> {
        let lookback = signal.get_int_or("lookback", 20);
        let threshold = signal.get_float_or("threshold", 0.0);

        if !signal.parameters.contains_key("lookback") {
            writeln!(
                pine,
                "sig_lookback = input.int({}, title=\"ROC Lookback\")",
                lookback
            )?;
        }
        if !signal.parameters.contains_key("threshold") {
            writeln!(
                pine,
                "sig_threshold = input.float({}, title=\"ROC Threshold\")",
                threshold
            )?;
        }

        writeln!(pine, "roc = ta.roc(close, sig_lookback)")?;
        writeln!(pine, "long_signal = roc > sig_threshold and roc[1] <= sig_threshold")?;
        writeln!(pine, "short_signal = roc < -sig_threshold and roc[1] >= -sig_threshold")?;

        Ok(())
    }

    fn write_aroon_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let lookback = signal.get_int_or("lookback", 25);

        if !signal.parameters.contains_key("lookback") {
            writeln!(
                pine,
                "sig_lookback = input.int({}, title=\"Aroon Lookback\")",
                lookback
            )?;
        }

        writeln!(pine, "aroon_up = 100 * (sig_lookback - ta.highestbars(high, sig_lookback + 1)) / sig_lookback")?;
        writeln!(pine, "aroon_down = 100 * (sig_lookback - ta.lowestbars(low, sig_lookback + 1)) / sig_lookback")?;
        writeln!(pine, "long_signal = ta.crossover(aroon_up, aroon_down)")?;
        writeln!(pine, "short_signal = ta.crossunder(aroon_up, aroon_down)")?;

        Ok(())
    }

    fn write_trend_flip_signal(
        &self,
        pine: &mut String,
        signal: &ComponentArtifact,
    ) -> ExportResult<()> {
        let lookback = signal.get_int_or("lookback", 20);

        if !signal.parameters.contains_key("lookback") {
            writeln!(
                pine,
                "sig_lookback = input.int({}, title=\"Trend Lookback\")",
                lookback
            )?;
        }

        writeln!(pine, "trend_ma = ta.sma(close, sig_lookback)")?;
        writeln!(pine, "uptrend = close > trend_ma")?;
        writeln!(pine, "long_signal = uptrend and not uptrend[1]")?;
        writeln!(pine, "short_signal = not uptrend and uptrend[1]")?;

        Ok(())
    }

    fn write_position_logic(
        &self,
        pine: &mut String,
        pm: &ComponentArtifact,
    ) -> ExportResult<()> {
        if self.include_comments {
            writeln!(pine, "// ===== POSITION MANAGER: {} =====", pm.name)?;
        }

        match pm.name.as_str() {
            "AtrTrailingStop" | "atr_trailing" | "atr_trailing_stop" => {
                self.write_atr_trailing(pine, pm)?;
            }
            "ChandelierExit" | "chandelier" | "chandelier_exit" => {
                self.write_chandelier(pine, pm)?;
            }
            "PercentTrailing" | "percent_trailing" => {
                self.write_percent_trailing(pine, pm)?;
            }
            "FixedStop" | "fixed_stop" => {
                self.write_fixed_stop(pine, pm)?;
            }
            "MaxHoldingPeriod" | "max_holding" | "max_holding_period" => {
                self.write_max_holding(pine, pm)?;
            }
            "TimeDecayStop" | "time_decay" | "time_decay_stop" => {
                self.write_time_decay(pine, pm)?;
            }
            _ => {
                // Default: use simple trailing stop
                if self.include_comments {
                    writeln!(
                        pine,
                        "// Note: {} not directly supported, using ATR trailing",
                        pm.name
                    )?;
                }
                self.write_atr_trailing(pine, pm)?;
            }
        }

        writeln!(pine)?;
        Ok(())
    }

    fn write_atr_trailing(&self, pine: &mut String, pm: &ComponentArtifact) -> ExportResult<()> {
        let period = pm.get_int_or("period", 14);
        let multiplier = pm.get_float_or("multiplier", 2.0);

        if !pm.parameters.contains_key("period") {
            writeln!(
                pine,
                "pm_period = input.int({}, title=\"ATR Period\")",
                period
            )?;
        }
        if !pm.parameters.contains_key("multiplier") {
            writeln!(
                pine,
                "pm_multiplier = input.float({}, title=\"ATR Multiplier\")",
                multiplier
            )?;
        }

        writeln!(pine, "atr_val = ta.atr(pm_period)")?;
        writeln!(pine, "long_stop = close - pm_multiplier * atr_val")?;
        writeln!(pine, "short_stop = close + pm_multiplier * atr_val")?;

        // Track trailing stop since entry
        writeln!(pine, "var float trail_stop = na")?;
        writeln!(pine, "if strategy.position_size > 0")?;
        writeln!(pine, "    trail_stop := math.max(nz(trail_stop), long_stop)")?;
        writeln!(pine, "else if strategy.position_size < 0")?;
        writeln!(pine, "    trail_stop := math.min(nz(trail_stop, 999999), short_stop)")?;
        writeln!(pine, "else")?;
        writeln!(pine, "    trail_stop := na")?;

        writeln!(pine, "exit_long = strategy.position_size > 0 and close < trail_stop")?;
        writeln!(pine, "exit_short = strategy.position_size < 0 and close > trail_stop")?;

        Ok(())
    }

    fn write_chandelier(&self, pine: &mut String, pm: &ComponentArtifact) -> ExportResult<()> {
        let period = pm.get_int_or("period", 22);
        let multiplier = pm.get_float_or("multiplier", 3.0);

        if !pm.parameters.contains_key("period") {
            writeln!(
                pine,
                "pm_period = input.int({}, title=\"Chandelier Period\")",
                period
            )?;
        }
        if !pm.parameters.contains_key("multiplier") {
            writeln!(
                pine,
                "pm_multiplier = input.float({}, title=\"Chandelier Multiplier\")",
                multiplier
            )?;
        }

        writeln!(pine, "highest_high = ta.highest(high, pm_period)")?;
        writeln!(pine, "lowest_low = ta.lowest(low, pm_period)")?;
        writeln!(pine, "atr_val = ta.atr(pm_period)")?;
        writeln!(pine, "chandelier_long = highest_high - pm_multiplier * atr_val")?;
        writeln!(pine, "chandelier_short = lowest_low + pm_multiplier * atr_val")?;

        writeln!(pine, "exit_long = strategy.position_size > 0 and close < chandelier_long")?;
        writeln!(pine, "exit_short = strategy.position_size < 0 and close > chandelier_short")?;

        Ok(())
    }

    fn write_percent_trailing(
        &self,
        pine: &mut String,
        pm: &ComponentArtifact,
    ) -> ExportResult<()> {
        let percent = pm.get_float_or("percent", 5.0);

        if !pm.parameters.contains_key("percent") {
            writeln!(
                pine,
                "pm_percent = input.float({}, title=\"Trailing %\")",
                percent
            )?;
        }

        writeln!(pine, "var float entry_price = na")?;
        writeln!(pine, "var float max_price = na")?;
        writeln!(pine, "var float min_price = na")?;

        writeln!(pine, "if strategy.position_size > 0")?;
        writeln!(pine, "    if strategy.position_size[1] <= 0")?;
        writeln!(pine, "        entry_price := close")?;
        writeln!(pine, "        max_price := close")?;
        writeln!(pine, "    max_price := math.max(max_price, close)")?;
        writeln!(pine, "else if strategy.position_size < 0")?;
        writeln!(pine, "    if strategy.position_size[1] >= 0")?;
        writeln!(pine, "        entry_price := close")?;
        writeln!(pine, "        min_price := close")?;
        writeln!(pine, "    min_price := math.min(min_price, close)")?;

        writeln!(pine, "exit_long = strategy.position_size > 0 and close < max_price * (1 - pm_percent / 100)")?;
        writeln!(pine, "exit_short = strategy.position_size < 0 and close > min_price * (1 + pm_percent / 100)")?;

        Ok(())
    }

    fn write_fixed_stop(&self, pine: &mut String, pm: &ComponentArtifact) -> ExportResult<()> {
        let stop_pct = pm.get_float_or("stop_percent", 2.0);

        if !pm.parameters.contains_key("stop_percent") {
            writeln!(
                pine,
                "pm_stop_percent = input.float({}, title=\"Stop %\")",
                stop_pct
            )?;
        }

        writeln!(pine, "var float entry_price = na")?;
        writeln!(pine, "if strategy.position_size != 0 and strategy.position_size[1] == 0")?;
        writeln!(pine, "    entry_price := close")?;

        writeln!(pine, "exit_long = strategy.position_size > 0 and close < entry_price * (1 - pm_stop_percent / 100)")?;
        writeln!(pine, "exit_short = strategy.position_size < 0 and close > entry_price * (1 + pm_stop_percent / 100)")?;

        Ok(())
    }

    fn write_max_holding(&self, pine: &mut String, pm: &ComponentArtifact) -> ExportResult<()> {
        let max_bars = pm.get_int_or("max_bars", 20);

        if !pm.parameters.contains_key("max_bars") {
            writeln!(
                pine,
                "pm_max_bars = input.int({}, title=\"Max Bars Held\")",
                max_bars
            )?;
        }

        writeln!(pine, "var int bars_held = 0")?;
        writeln!(pine, "if strategy.position_size != 0")?;
        writeln!(pine, "    bars_held := bars_held + 1")?;
        writeln!(pine, "else")?;
        writeln!(pine, "    bars_held := 0")?;

        writeln!(pine, "exit_long = strategy.position_size > 0 and bars_held >= pm_max_bars")?;
        writeln!(pine, "exit_short = strategy.position_size < 0 and bars_held >= pm_max_bars")?;

        Ok(())
    }

    fn write_time_decay(&self, pine: &mut String, pm: &ComponentArtifact) -> ExportResult<()> {
        let initial_stop = pm.get_float_or("initial_stop", 5.0);
        let decay_per_bar = pm.get_float_or("decay_per_bar", 0.1);

        if !pm.parameters.contains_key("initial_stop") {
            writeln!(
                pine,
                "pm_initial_stop = input.float({}, title=\"Initial Stop %\")",
                initial_stop
            )?;
        }
        if !pm.parameters.contains_key("decay_per_bar") {
            writeln!(
                pine,
                "pm_decay_per_bar = input.float({}, title=\"Decay per Bar %\")",
                decay_per_bar
            )?;
        }

        writeln!(pine, "var float entry_price = na")?;
        writeln!(pine, "var int bars_held = 0")?;

        writeln!(pine, "if strategy.position_size != 0 and strategy.position_size[1] == 0")?;
        writeln!(pine, "    entry_price := close")?;
        writeln!(pine, "    bars_held := 0")?;
        writeln!(pine, "else if strategy.position_size != 0")?;
        writeln!(pine, "    bars_held := bars_held + 1")?;

        writeln!(pine, "current_stop = pm_initial_stop - bars_held * pm_decay_per_bar")?;
        writeln!(pine, "current_stop := math.max(current_stop, 0.5)")?;

        writeln!(pine, "exit_long = strategy.position_size > 0 and close < entry_price * (1 - current_stop / 100)")?;
        writeln!(pine, "exit_short = strategy.position_size < 0 and close > entry_price * (1 + current_stop / 100)")?;

        Ok(())
    }

    fn write_filter_logic(
        &self,
        pine: &mut String,
        filter: &ComponentArtifact,
    ) -> ExportResult<()> {
        if self.include_comments {
            writeln!(pine, "// ===== FILTER: {} =====", filter.name)?;
        }

        match filter.name.as_str() {
            "AdxFilter" | "adx" | "adx_filter" => {
                let period = filter.get_int_or("period", 14);
                let threshold = filter.get_float_or("threshold", 25.0);

                if !filter.parameters.contains_key("period") {
                    writeln!(
                        pine,
                        "flt_period = input.int({}, title=\"ADX Period\")",
                        period
                    )?;
                }
                if !filter.parameters.contains_key("threshold") {
                    writeln!(
                        pine,
                        "flt_threshold = input.float({}, title=\"ADX Threshold\")",
                        threshold
                    )?;
                }

                writeln!(pine, "[di_plus, di_minus, adx_val] = ta.dmi(flt_period, flt_period)")?;
                writeln!(pine, "filter_pass = adx_val > flt_threshold")?;
            }
            "MaRegimeFilter" | "ma_regime" | "ma_regime_filter" => {
                let period = filter.get_int_or("period", 200);

                if !filter.parameters.contains_key("period") {
                    writeln!(
                        pine,
                        "flt_period = input.int({}, title=\"Regime MA Period\")",
                        period
                    )?;
                }

                writeln!(pine, "regime_ma = ta.sma(close, flt_period)")?;
                writeln!(pine, "filter_pass = close > regime_ma")?;
            }
            "VolatilityFilter" | "volatility" | "volatility_filter" => {
                let min_atr = filter.get_float_or("min_atr", 0.01);

                if !filter.parameters.contains_key("min_atr") {
                    writeln!(
                        pine,
                        "flt_min_atr = input.float({}, title=\"Min ATR %\")",
                        min_atr
                    )?;
                }

                writeln!(pine, "atr_pct = ta.atr(14) / close * 100")?;
                writeln!(pine, "filter_pass = atr_pct > flt_min_atr")?;
            }
            "NoFilter" | "no_filter" | "none" => {
                writeln!(pine, "filter_pass = true")?;
            }
            _ => {
                writeln!(pine, "filter_pass = true")?;
            }
        }

        writeln!(pine)?;
        Ok(())
    }

    fn write_entry_exit(&self, pine: &mut String, artifact: &StrategyArtifact) -> ExportResult<()> {
        if self.include_comments {
            writeln!(pine, "// ===== ENTRY/EXIT LOGIC =====")?;
        }

        let has_filter = artifact.signal_filter.is_some();
        let filter_cond = if has_filter { " and filter_pass" } else { "" };

        writeln!(pine, "if long_signal{}", filter_cond)?;
        writeln!(pine, "    strategy.entry(\"Long\", strategy.long)")?;

        // Check if short signals are allowed
        writeln!(pine, "if short_signal{}", filter_cond)?;
        writeln!(pine, "    strategy.entry(\"Short\", strategy.short)")?;

        writeln!(pine)?;
        writeln!(pine, "if exit_long")?;
        writeln!(pine, "    strategy.close(\"Long\")")?;
        writeln!(pine, "if exit_short")?;
        writeln!(pine, "    strategy.close(\"Short\")")?;

        writeln!(pine)?;
        Ok(())
    }

    fn write_plotting(
        &self,
        pine: &mut String,
        artifact: &StrategyArtifact,
    ) -> ExportResult<()> {
        if self.include_comments {
            writeln!(pine, "// ===== PLOTTING =====")?;
        }

        // Plot signal levels based on signal type
        match artifact.signal_generator.name.as_str() {
            "DonchianBreakout" | "donchian_breakout" | "FiftyTwoWeekBreakout" | "fifty_two_week" => {
                writeln!(pine, "plot(donchian_high, color=color.new(color.green, 50), title=\"Upper Channel\")")?;
                writeln!(pine, "plot(donchian_low, color=color.new(color.red, 50), title=\"Lower Channel\")")?;
            }
            "MaCrossover" | "ma_crossover" => {
                writeln!(pine, "plot(fast_ma, color=color.blue, title=\"Fast MA\")")?;
                writeln!(pine, "plot(slow_ma, color=color.orange, title=\"Slow MA\")")?;
            }
            "Supertrend" | "supertrend" => {
                writeln!(pine, "plot(supertrend, color=direction < 0 ? color.green : color.red, title=\"Supertrend\")")?;
            }
            "BollingerBreakout" | "bollinger_breakout" => {
                writeln!(pine, "plot(bb_upper, color=color.new(color.blue, 50), title=\"BB Upper\")")?;
                writeln!(pine, "plot(bb_middle, color=color.new(color.gray, 50), title=\"BB Middle\")")?;
                writeln!(pine, "plot(bb_lower, color=color.new(color.blue, 50), title=\"BB Lower\")")?;
            }
            "ParabolicSar" | "parabolic_sar" => {
                writeln!(pine, "plot(sar, style=plot.style_circles, color=close > sar ? color.green : color.red, title=\"SAR\")")?;
            }
            _ => {}
        }

        // Plot trailing stop if applicable
        writeln!(pine, "plot(trail_stop, color=color.new(color.red, 30), style=plot.style_linebr, title=\"Trailing Stop\")")?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::artifact::ComponentArtifact;

    #[test]
    fn test_generate_donchian() {
        let artifact = StrategyArtifact::new(
            "test".to_string(),
            ComponentArtifact::new("DonchianBreakout").param("lookback", 20.into()),
            ComponentArtifact::new("AtrTrailingStop")
                .param("period", 14.into())
                .param("multiplier", 2.0.into()),
            ComponentArtifact::new("NextOpenFill"),
        );

        let generator = PineGenerator::new();
        let pine = generator.generate(&artifact).unwrap();

        assert!(pine.contains("//@version=6"));
        assert!(pine.contains("strategy("));
        assert!(pine.contains("donchian_high"));
        assert!(pine.contains("trail_stop"));
    }

    #[test]
    fn test_generate_with_filter() {
        let artifact = StrategyArtifact::new(
            "test".to_string(),
            ComponentArtifact::new("MaCrossover"),
            ComponentArtifact::new("PercentTrailing"),
            ComponentArtifact::new("NextOpenFill"),
        )
        .with_filter(ComponentArtifact::new("AdxFilter").param("threshold", 25.0.into()));

        let generator = PineGenerator::new();
        let pine = generator.generate(&artifact).unwrap();

        assert!(pine.contains("filter_pass"));
        assert!(pine.contains("adx_val"));
    }

    #[test]
    fn test_generate_without_comments() {
        let artifact = StrategyArtifact::new(
            "test".to_string(),
            ComponentArtifact::new("DonchianBreakout"),
            ComponentArtifact::new("AtrTrailingStop"),
            ComponentArtifact::new("NextOpenFill"),
        );

        let generator = PineGenerator::new().with_comments(false);
        let pine = generator.generate(&artifact).unwrap();

        assert!(!pine.contains("// Generated by"));
        assert!(!pine.contains("// ====="));
    }

    #[test]
    fn test_unsupported_signal() {
        let artifact = StrategyArtifact::new(
            "test".to_string(),
            ComponentArtifact::new("UnsupportedSignal"),
            ComponentArtifact::new("AtrTrailingStop"),
            ComponentArtifact::new("NextOpenFill"),
        );

        let generator = PineGenerator::new();
        let result = generator.generate(&artifact);

        assert!(result.is_err());
        if let Err(ExportError::UnsupportedComponent { component }) = result {
            assert_eq!(component, "UnsupportedSignal");
        } else {
            panic!("Expected UnsupportedComponent error");
        }
    }
}
